language: go
go:
- "1.12.x"
env:
  global:
    GOFLAGS=-mod=vendor
install:
- go get github.com/mitchellh/gox
script:
- make test
- make vet
- make bin VERSION=$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: s3NEfeyucZEyhFy+/eOncbmPtDQV8b85BQsK7ufN0QNhui5NNOShozK9C5zoH6J9m89/RpWofaXrawuIiQgkWbtEONQs+PFqcmNCq3u5UrGtNb374INvPj/Osd2phxjhtnb9+Xh2jE9/U9qkYDcAULWYIGf1stWntmtJupvGNfFBP2IXligqCbyFF9iuRl3FT6LsQyAEk8ziR/qajMOeA+ifluslXOrOjXuBYN8WTD30e4zE7XD4HAVXWeLyzYA7JVqU8ZZBpORbnWhQ5mGNvB2sIukgP7d0/ql5KkEK4UZRGCNMC0D0Ry5ewFNHWPLquJO18aN6LFRq78h5DaibGsn0BcsumDQxUGsllBLJp4wyOtq9v5RgaWJtyUTKrp1i9Zlk4gTkTZA9X0BvauVh55o8YgSiKlLAmYRWpgWcePfJX1bAVxEeB11xGidMJhhctL2iLBtNwviV094PThd2x9rKJm5jSoXztaAaRu37gU8HIWe6lmbM5Dg0GqUbv7Vd8jtqr7ewogP60dJx61QmjxrLE6WY2+hK4PRg/TE5zuw9lxXu4Q2P22MqX3JuD0nAgPJaGQqpO6r9LKrX5kONDuK3FUqSF3P9O8XtSJmeoEvkBkGZkDuk+siqrV8clFCrlIdzk+iRAuuvUmDnyXTcflCkW6Yvjp146m84THkY568=
  file: pkg/terraform-provider-cloudhealth_*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
